# Site settings
title: Urban App Makers
email: admin@urbanappmaker.com
description: >
  Official documentation for Urban App
baseurl: ""
url: http://docs.urbanappmaker.com
timezone: America/Denver

images:
    logo: /images/logo.svg

# Build settings
collections:
    api:
        output: true
source: src
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
  style: :compressed

# Plugin

gems:
- jekyll-sitemap
